from .util import *

FPS = 0
WIDTH, HEIGHT = 960, 580

DIR_IMAGES = 'files/assets/images/'
DIR_SFX = 'files/assets/sound/sfx/'

# Player
PLAYER_SPEED = 0.5
PLAYER_LIVES = 3

PLAYER_INIT_POS = WIDTH//15, HEIGHT//2

# Bullet
BULLET_ACCELERATION = 0.25
BULLET_COOLDOWN = 0.5

N_BULLETS_IN_MAGAZINE = 6
BULLET_RELOAD_TIME = 0.5


# Explosions
EXPLOSION_ANIMATION_SPEED = 0.03

# Stars
STARS_ON_SCREEN = 60
